import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:stima/features/companies/models/company_entrance.dart';
import 'package:stima/features/companies/models/company_form_data.dart';
import 'package:stima/features/companies/models/company_placemark.dart';

part 'company.freezed.dart';
part 'company.g.dart';

@freezed
abstract class Company with _$Company {
  /// The unique identifier for a company
  ///
  /// The id is generated by cloud function when a new company is created.
  @override
  final int id;

  @override
  final String name;

  @override
  final String contactPersonName;

  @override
  final String? phoneNumber;

  @override
  final String? email;

  @override
  final String? address;

  @override
  final bool isActive;

  @override
  final String? kmlMapFileLink;

  @JsonSerializable(explicitToJson: true)
  Company._({
    int? id,
    String? name,
    String? contactPersonName,
    String? phoneNumber,
    List<CompanyEntrance>? entrances,
    List<CompanyPlacemark>? placemarks,
    bool? isActive,
    this.email,
    this.address,
    this.kmlMapFileLink,
  }) : id = id ?? 0,
       name = name ?? '',
       contactPersonName = contactPersonName ?? '',
       phoneNumber = phoneNumber ?? '',
       isActive = isActive ?? true;

  @JsonSerializable(explicitToJson: true)
  factory Company.data({
    required int id,
    required String name,
    required String contactPersonName,
    String? phoneNumber,
    String? email,
    String? address,
    bool? isActive,
    String? kmlMapFileLink,
  }) = _CompanyData;

  // Factory constructor for creating a new Company instance
  @JsonSerializable(explicitToJson: true)
  factory Company.fromForm(CompanyFormData formData) {
    return Company.data(
      id: 0,
      name: formData.companyName,
      contactPersonName: formData.contactPersonName,
      phoneNumber: formData.phoneNumber,
      email: formData.email,
      address: formData.address,
      isActive: true,
      kmlMapFileLink: formData.fileInfo?.kmlMapFileLink,
    );
  }

  factory Company.fromJson(Map<String, dynamic> json) =>
      _$CompanyFromJson(json);

  bool get hasPhoneNumber => phoneNumber != null && phoneNumber!.isNotEmpty;
}
